--- #YAML:1.0
name: Data-Page
version: 0.16
license: perl
distribution_type: module
requires:
  Test::More: 0.1
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
