--- #YAML:1.0
name: Data-Page
version: 0.18
license: perl
distribution_type: module
requires:
  Test::More: 0.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Data::Page:
    file: lib/Data/Page.pm
    version: 0.18
generated_by: Module::Build version 0.19
